---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-pods
  namespace: nginx-cap1
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adminbinding-pods
  namespace: nginx-cap1
subjects:
  - apiGroup: ""
    kind: User
    name: podadmin
roleRef:
    apiGroup: ""
    kind: Role
    name: admin-pods
