---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dply
  namespace: nginx-cap1
  labels:
    app: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      name: nginx-dply
      labels:
        app: project1
    spec:
      containers:
        - name: nginxapp
          image: nginx:latest
          ports:
          - containerPort: 80
            name: nginxapp
          resources:
             limits:
               cpu: 200m

