---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      name: postgres-pod
      labels:
        app: project1
    spec:
      containers:
        - name: postgres1
          image: postgres:13.10-alpine

