---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    app: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      name: springapp-pod
      labels:
        app: project1
    spec:
      containers:
        - name: springapp1
          image: marcelalt/springsql:latest

